// licilibre — fix3.js — DEFINITIVO
// node fix3.js
const fs = require('fs');
const path = require('path');

const supabaseContent = [
  "import { createClient } from '@supabase/supabase-js';",
  "",
  "// Client creat lazily per evitar errors durant el build",
  "let _client = null;",
  "function getClient() {",
  "  if (_client) return _client;",
  "  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;",
  "  const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;",
  "  if (!url || !key) return null;",
  "  _client = createClient(url, key);",
  "  return _client;",
  "}",
  "",
  "export async function cercarLicitacions(filtres) {",
  "  const supabase = getClient();",
  "  if (!supabase) return { licitacions: [], total: 0, pagina: 1, per_pagina: 20 };",
  "  const { q, ccaa, fuente, urgencia, order, limit = 20, offset = 0 } = filtres;",
  "  try {",
  "    let query = supabase.from('licitaciones_actives').select('*', { count: 'exact' });",
  "    if (q && q.trim()) {",
  "      const qs = q.trim();",
  "      query = query.or('titulo.ilike.%' + qs + '%,organismo.ilike.%' + qs + '%');",
  "    }",
  "    if (ccaa) query = query.ilike('ccaa', '%' + ccaa + '%');",
  "    if (fuente) query = query.eq('fuente', fuente);",
  "    if (urgencia) query = query.eq('urgencia', urgencia);",
  "    if (order === 'pressupost') query = query.order('pressupost_base', { ascending: false, nullsFirst: false });",
  "    else if (order === 'recent') query = query.order('data_publicacio', { ascending: false });",
  "    else query = query.order('dies_restants', { ascending: true, nullsFirst: false });",
  "    const { data, error, count } = await query.range(offset, offset + limit - 1);",
  "    if (error) { console.error('Supabase error:', error); return { licitacions: [], total: 0, pagina: 1, per_pagina: limit }; }",
  "    return { licitacions: data || [], total: count || 0, pagina: Math.floor(offset / limit) + 1, per_pagina: limit };",
  "  } catch (e) {",
  "    console.error('cercarLicitacions error:', e);",
  "    return { licitacions: [], total: 0, pagina: 1, per_pagina: limit };",
  "  }",
  "}",
  "",
  "export async function getLicitacio(id) {",
  "  const supabase = getClient();",
  "  if (!supabase) return null;",
  "  try {",
  "    const { data, error } = await supabase.from('licitaciones').select('*').eq('id', id).single();",
  "    if (error) return null;",
  "    return data;",
  "  } catch (e) { return null; }",
  "}",
  "",
  "export async function createAlerta(alerta) {",
  "  const supabase = getClient();",
  "  if (!supabase) throw new Error('Supabase no disponible');",
  "  const { data, error } = await supabase",
  "    .from('alertes')",
  "    .insert({ ...alerta, frequencia: alerta.frequencia || 'diaria' })",
  "    .select('id').single();",
  "  if (error) throw error;",
  "  return data;",
  "}",
].join('\n');

fs.writeFileSync(path.join(__dirname, 'web', 'lib', 'supabase.ts'), supabaseContent, 'utf8');
console.log('OK — supabase.ts reescrit amb client lazy');
console.log('Ara: git add web/lib/supabase.ts');
